# Generated by Django 4.2.20 on 2025-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarrification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunite",
            name="adresse_chantier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="descriptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="franchises_assure_maître_ouvrage",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="franchises_dommages_ouvrage",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="franchises_maintenance_visite",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="garanties_dommages_ouvrage",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="garanties_maintenance_visite",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="garanties_mesure_conservatoire",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="garanties_responsabilité_civile",
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="tarif_do",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="tarif_trc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="type_de_garantie",
            field=models.CharField(
                choices=[
                    ("TRC", "TRC seule"),
                    ("DO", "DO seule"),
                    ("TRCDO", "TRC + DO"),
                ],
                max_length=5,
            ),
        ),
    ]
