# Generated by Django 4.2.20 on 2025-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarrification", "0002_opportunite_adresse_chantier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunite",
            name="prime_seul_do",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="prime_seul_duo",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="prime_seul_trc",
            field=models.FloatField(default=0.0),
        ),
    ]
