# Generated by Django 4.2.20 on 2025-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tarrification",
            "0003_opportunite_prime_seul_do_opportunite_prime_seul_duo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunite",
            name="cout",
            field=models.FloatField(default=0.0),
        ),
    ]
