# Generated by Django 4.2.20 on 2025-05-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tarrification",
            "0006_alter_opportunite_cout_alter_opportunite_existant_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunite",
            name="taux_seul",
        ),
    ]
