# Generated by Django 4.2.20 on 2025-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarrification", "0007_remove_opportunite_taux_seul"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunite",
            name="tarif_do",
        ),
        migrations.RemoveField(
            model_name="opportunite",
            name="tarif_trc",
        ),
        migrations.AddField(
            model_name="opportunite",
            name="taux_do",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunite",
            name="taux_trc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="cout",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="franchises_assure_maître_ouvrage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="franchises_dommages_ouvrage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="franchises_maintenance_visite",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="garanties_dommages_ouvrage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="garanties_maintenance_visite",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="garanties_mesure_conservatoire",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="garanties_responsabilité_civile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="prime_seul_do",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="prime_seul_duo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunite",
            name="prime_seul_trc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
